name: fast_snarf
channels:
  - anaconda
  - conda-forge
  - pytorch
  - pytorch3d
  - defaults
dependencies:
  - python=3.8
  - pytorch=1.10.0
  - torchvision
  - cudatoolkit=10.2
  - iopath
  - fvcore
  - pytorch3d
  - pip
  - pip:
    - chumpy
    - scikit-image==0.18.2
    - imageio-ffmpeg
    - trimesh
    - wandb
    - tqdm
    - pytorch-lightning==1.5.0
    - opencv-python==4.5.2.54
    - hydra-core==1.0.6
    - setuptools==59.5.0
    - Cython
    - matplotlib
    - ninja