datamodule:
  _target_: lib.dataset.dfaust.DFaustDataModule
  dataset_path: ./data/test_snarf_release/DFaust_processed
  subject: ${subject}
  num_workers: 10
  batch_size: 8
  points_per_frame: 2000

